package: cloud.lazycat.app.photo
lzc-sdk-version: v0.0.0-20251107100445-bf41422ed4ef
version: 2.0.0-899c0b
name: 懒猫相册
description: 懒猫相册
license: https://choosealicense.com/licenses/mit/
homepage: 
author: linakesi
locales:
  zh:
    name: 懒猫相册
    description: 懒猫相册
  en:
    name: Photos
    description: Photo App
runtime_dependencies:
  os: '>= 0.3.7'
application:
  image: registry.lazycat.cloud/lzc/lzc-photo:3295c1ec
  background_task: true
  subdomain: photo
  mem_limit: 4294967296
  routes:
    - /=file:///lzcapp/pkg/content/web
    - /api/=exec://5678,/lzcapp/pkg/content/app.sh
    - /appstoreApi/=https://appstore.lazycat.cloud/api
  public_path:
    - /api/transfer/download/static
    - /api/ai/search/path
  health_check:
    test_url: http://localhost:5678/healthz
    start_period: 43200s
  gpu_accel: true
  depends_on:
    - postgres
    - weaviate
  environment:
    - TZ=UTC
ext_config:
  enable_document_access: true
  disable_grpc_web_on_root: true
services:
  weaviate:
    command: '--host 0.0.0.0 --port 8080 --scheme http'
    image: registry.lazycat.cloud/lzc/weaviate:1.28.2-2b40d6e
    binds:
      - /lzcapp/var/vdb:/var/lib/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DISK_USE_WARNING_PERCENTAGE=90
      - DISK_USE_READONLY_PERCENTAGE=98
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=
      - CLUSTER_HOSTNAME=vector_db
      - RAFT_ENABLE_ONE_NODE_RECOVERY=true
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - http://localhost:8080/v1/.well-known/ready
        - '-O'
        - /dev/null
      start_period: 300s
  photosearch:
    init: true
    image: registry.lazycat.cloud/ai/photosearch:18c29f07
    command: bash -c 'date;python server.py'
  postgres:
    image: registry.lazycat.cloud/lzc/postgres:17-alpine3.20
    environment:
      - POSTGRES_USER=lzc
      - POSTGRES_DB=lzc
      - POSTGRES_ROOT_PASSWORD=lzc
      - POSTGRES_PASSWORD=lzc
    binds:
      - /lzcapp/var/postgresql:/var/lib/postgresql/data
      - /lzcapp/var/postgres-runtime:/var/run/postgresql
    health_check:
      test:
        - CMD
        - pg_isready
        - '-U'
        - lzc
      start_period: 600s
