lzc-sdk-version: 0.1
package: cloud.lazycat.app.urldb
version: 1.2.3
name: 老九网盘资源数据库
description: 一个现代化的网盘资源数据库，支持多网盘自动化转存分享
author: ctwj
homepage: https://github.com/ctwj/urldb
license: GPL-3.0
application:
  subdomain: urldb
  background_task: true
  multi_instance: false
  public_path:
    - /
  routes:
    - /=http://nginx:80/
services:
  postgres:
    image: registry.lazycat.cloud/edward/library/postgres:027fe138ecb1a7cb
    environment:
      - POSTGRES_DB=url_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    binds:
      - /lzcapp/var/postgres_data:/var/lib/postgresql/data
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      start_period: 30s
  backend:
    image: registry.lazycat.cloud/edward/ctwj/urldb-backend:562ae9b70a99ed1e
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=url_db
      - PORT=8080
      - TIMEZONE=Asia/Shanghai
    depends_on:
      - postgres
    binds:
      - /lzcapp/var/uploads:/root/uploads
  frontend:
    image: registry.lazycat.cloud/edward/ctwj/urldb-frontend:6f02425a96c9d123
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_SERVER=http://backend:8080/api
    depends_on:
      - backend
  nginx:
    image: registry.lazycat.cloud/edward/library/nginx:66ed6c4c9590f7e5
    binds:
      - /lzcapp/pkg/content/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /lzcapp/pkg/content/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
