name: Search MicroServer
locales:
  zh:
    name: 搜索微服
    description: 随心所欲的搜索
  en:
    name: Search MicroServer
    description: Search Any file in Lazycat MicroServer
  ja:
    name: サーチ・マイクロサーバ
    description: 好きなように検索
package: cloud.lazycat.aipod.rag
version: 0.3.3
description: Search Any file in Lazycat MicroServer
license: https://choosealicense.com/licenses/mit/
homepage: 
author: 
application:
  subdomain: rag
  gpu_accel: true
  routes:
    - /=http://caddy:80
  public_path:
    - /v1/
    - /backend/filechat/
services:
  caddy:
    image: registry.lazycat.cloud/catdogai/caddy-aipod:65e058ce
    setup_script: |
      cat <<'EOF' > /etc/caddy/Caddyfile
      {
              auto_https off
              http_port 80
              https_port 0
      }
      :80 {
              handle /backend/* {
                      uri strip_prefix /backend
                      reverse_proxy backend:8070
              }
              handle /backend/filechat/* {
                      uri strip_prefix /backend/filechat
                      reverse_proxy backend_filechat:3000
              }
              handle /backend/rag/* {
                      uri strip_prefix /backend/rag
                      reverse_proxy backend_rag:3001
              }
              handle {
                      route {
                              lzcaipod
                              root * /lzcapp/pkg/content/dist/
                              try_files {path} /index.html

                              header Cache-Control "max-age=60, private, must-revalidate"
                              file_server
                      }
              }
      }
      EOF
      cat /etc/caddy/Caddyfile
  backend_videorag:
    init: true
    mem_limit: 5G
    image: registry.lazycat.cloud/x/videorag/rag:93c36f3
    environment:
      - ASR_URL=https://asr-ai.${LAZYCAT_BOX_DOMAIN}
      - CLIP_URL=https://clip-ai.${LAZYCAT_BOX_DOMAIN}
      - BLIP_URL=https://blip-ai.${LAZYCAT_BOX_DOMAIN}
      - CACHE_DIR=/lzcapp/var/videorag_v2
    health_check:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3000/health
      start_period: 60s
  backend_jieba:
    image: registry.lazycat.cloud/catdogai/jieba:0.42.1-403da521
  backend_filechat:
    init: true
    image: registry.lazycat.cloud/x/filechat:603cb4a
    environment:
      - BACKEND_URL=http://backend:8070/embedding/search
      - BACKEND_TIMEOUT=300
      - LLM_API_BASE=https://ollama-ai.${LAZYCAT_BOX_DOMAIN}/v1
      - LLM_ANSWER_MODEL=qwen3:30b-a3b
      - LLM_QUERY_MODEL=qwen3:30b-a3b
      - DB_URL=postgresql+asyncpg://postgres:temppassword@postgres:5432/postgres
      - DB_CHUNK_SIZE=3
  backend_rag:
    init: true
    image: registry.lazycat.cloud/x/rag:bb78b8b
    mem_limit: 5G
    environment:
      - EMBEDDING_BASE_URL=https://bgem3vllm-ai.${LAZYCAT_BOX_DOMAIN}/v1
      - EMBEDDING_MODEL=bge-m3
      - OCR_BASE_URL=https://ocr-ai.${LAZYCAT_BOX_DOMAIN}
      - DO_NOT_TRACK=true
      - SCARF_NO_ANALYTICS=true
      - AUTO_DOWNLOAD_NLTK=false
    health_check:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3001/health
      start_period: 60s
  backend:
    image: registry.lazycat.cloud/catdogai/backend:20250625
    entrypoint: /lzcapp/pkg/content/server.amd64
    environment:
      - OCR_BASE_URL=https://ocr-ai.${LAZYCAT_BOX_DOMAIN}
      - >-
        BGE_RERANKER_BASE_URL=https://bgererankerv2m3vllm-ai.${LAZYCAT_BOX_DOMAIN}
      - BGE_M3_BASE_URL=https://bgem3vllm-ai.${LAZYCAT_BOX_DOMAIN}
      - KEYWORD_BGE_M3_BASE_URL=https://bgem3vllm2-ai.${LAZYCAT_BOX_DOMAIN}
      - APP_VIDEORAG_CACHE_DIR=/lzcapp/var/videorag_v2
    depends_on:
      - postgres
      - backend_rag
  postgres:
    image: registry.lazycat.cloud/catdogai/postgres:17.4-pgvectorscale-202509121813
    binds:
      - /lzcapp/var/pg-v4:/var/lib/postgresql/data
      - /lzcapp/pkg/content/postgresql.conf:/etc/postgresql.conf
    command: '-c config_file=/etc/postgresql.conf'
    mem_limit: 2G
    shm_size: 2G
    environment:
      - POSTGRES_PASSWORD=temppassword
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=postgres
    health_check:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
      start_period: 60s
ext_config:
  enable_document_access: true
  enable_media_access: true
  permissions:
    - PERM_DOCKER_CAP_SYS_ADMIN
    - PERM_MEDIA_MOUNT_SHARED
