lzc-sdk-version: '0.1'
package: cloud.lazycat.app.ghostfolio
version: 2.185.0
name: Ghostfolio
description: Open Source Wealth Management Software
homepage: https://github.com/ghostfolio/ghostfolio
license: AGPL-3.0 license
application:
  subdomain: ghostfolio
  background_task: true
  multi_instance: false
  routes:
    - /=http://ghostfolio.cloud.lazycat.app.ghostfolio.lzcapp:3333/
  public_path:
    - /
services:
  ghostfolio-db:
    image: registry.lazycat.cloud/edward/library/postgres:8f4cf0232cbd1109
    environment:
      - POSTGRES_DB=ghostfoliodb
      - POSTGRES_USER=ghostfoliouser
      - POSTGRES_PASSWORD=ghostfoliopass
    binds:
      - /lzcapp/var/ghostfolio/db:/var/lib/postgresql/data
    health_check:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - ghostfoliodb
        - '-U'
        - ghostfoliouser
      start_period: 90s
  ghostfolio-redis:
    image: registry.lazycat.cloud/edward/library/redis:630b4b80b5d10832
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/ghostfolio/redis:/data
    health_check:
      test:
        - CMD
        - redis-cli
        - ping
      start_period: 10s
  ghostfolio:
    image: registry.lazycat.cloud/edward/ghostfolio/ghostfolio:318b1d13ab3c25bd
    environment:
      - NODE_ENV=production
      - >-
        ACCESS_TOKEN_SALT=dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      - >-
        JWT_SECRET_KEY=EIYUphmqESmtPYsVHziPuBizgVflRtXuIrXypYfFEjkZAQUXwpwzspRwgFaQztlw
      - REDIS_HOST=ghostfolio-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - >-
        DATABASE_URL=postgresql://ghostfoliouser:ghostfoliopass@ghostfolio-db:5432/ghostfoliodb?sslmode=prefer
    depends_on:
      - ghostfolio-db
      - ghostfolio-redis
    ports:
      - '3333:3333'
    health_check:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3333/api/v1/health || exit 1
      start_period: 60s
