lzc-sdk-version: v0.2.3-1414-ge396fd39
package: cloud.lazycat.shell.files
version: 2.4.2
name: 懒猫网盘
description: 懒猫云网盘
locales:
  zh:
    name: 懒猫网盘
    description: 懒猫云网盘
  en:
    name: Cloud Drive
    description: Cloud Drive App
license: https://choosealicense.com/licenses/mit/
homepage: 
author: 
runtime_dependencies:
  os: '>= 0.3.7'
application:
  image: registry.lazycat.cloud/lzc/lzc-files:v0.1.55
  gpu_accel: true
  background_task: true
  basic_auth_path:
    - /_lzc/files
  subdomain: file
  public_path:
    - /dav
  routes:
    - /api/=exec://3001,/lzcapp/pkg/content/app.sh
    - /files/=http://127.0.0.1:3001/files/
    - /dav=http://127.0.0.1:3001/dav
    - /dav/=http://127.0.0.1:3001/dav/
    - /owsync/=http://127.0.0.1:5002/
    - /=file:///lzcapp/pkg/content/dist
  ingress:
    - protocol: tcp
      port: 445
      service: smbserver
    - protocol: tcp
      port: 139
      service: smbserver
services:
  lzcai:
    image: registry.lazycat.cloud/ai/lzc-ai:6c28dce2
  tts:
    image: registry.lazycat.cloud/ai/funasr_cpp:48a508f8
  lzcmedia:
    image: registry.lazycat.cloud/lzc-media/lzc-media:bdfcdbe5
    cpus: 4
    environment:
      - MEDIA_ENCODE_VBR=1
      - MEDIA_ENCODE_SET_PARAM=1
  smbserver:
    image: registry.lazycat.cloud/lzc-files/smbserver:e4649cd
    depends_on:
      - smbforward
    environment:
      - DISABLE_AUTOMOUNT_AUTH=y
  smbforward:
    image: registry.lazycat.cloud/lzc-files/forwarder:e4649cd
    network_mode: host
    environment:
      - LZC_FILE_SMB_MODE=forward
      - ENABLE_WSDD=y
  mountserver:
    image: registry.lazycat.cloud/lzc-files/lzc-file-mount:703656b
ext_config:
  enable_bind_mime_globs: true
  enable_document_access: true
  enable_media_access: true
  disable_url_raw_path: true
  disable_grpc_web_on_root: true
  permissions:
    - PERM_DOCKER_CAP_SYS_ADMIN
    - PERM_OTHER_APP_DATA_ADMIN
    - PERM_MEDIA_MOUNT_SHARED
