package: cloud.lazycat.developer.tools
version: 0.3.2
name: 懒猫开发者工具
min_os_version: 1.1.0
locales:
  zh:
    name: 懒猫开发者工具
  en:
    name: Developer Toolkit
  ja:
    name: 開発者ツールキット
application:
  subdomain: dev
  background_task: true
  routes:
    - /__sshd=exec://80,/lzcapp/pkg/content/config/init.sh
    - /__rsync=exec://80,/lzcapp/pkg/content/debug.bridge forward-rsync
    - /resources/=file:///resources
    - /bannerfile=file:///lzcapp/pkg/content/config/bannerfile
    - /v2/=http://registry.cloud.lazycat.developer.tools.lzcapp:5000/v2/
    - /=file:///lzcapp/pkg/content/dist
    - /dozzle/=http://dozzle.cloud.lazycat.developer.tools.lzcapp:8080/dozzle/
    - /testflight/=https://testflight.lazycat.cloud/api
    - /api/=exec://8078,/lzcapp/pkg/content/debug.bridge server
  image: registry.lazycat.cloud/lzc/debug-bridge:v0.0.28
  public_path:
    - /v2/
    - /bannerfile
  ingress:
    - protocol: tcp
      port: 22222
    - protocol: tcp
      port: 873
    - protocol: tcp
      port: 874
services:
  registry-proxy:
    image: registry.lazycat.cloud/nginx:1.27.3
    network_mode: host
    binds:
      - /lzcapp/pkg/content/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - registry
  registry:
    image: registry.lazycat.cloud/registry:2
    binds:
      - /lzcapp/var/registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
  dozzle:
    image: registry.lazycat.cloud/catdog/amir20/dozzle:e675824d3a7cb863
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_BASE=/dozzle
      - DOCKER_HOST=unix:///lzcapp/run/lzc-docker/docker.sock
ext_config:
  permissions:
    - PERM_LZC_DOCKER_ADMIN
    - PERM_OTHER_APP_DATA_ADMIN
    - PERM_DOCKER_CAP_SYS_ADMIN
